"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { aiInsights, getApiBase } from "@/lib/api";
import { getStaffToken, clearStaffToken, getOperatorMerchant } from "@/lib/auth";
import MerchantSidebar from "@/components/MerchantSidebar";
import type { AIInsights } from "@fbgroup/api-client";

const PRIORITY_STYLE: Record<string, { bg: string; fg: string; label: string }> = {
  high: { bg: "#fee2e2", fg: "#991b1b", label: "High priority" },
  medium: { bg: "#fef9c3", fg: "#854d0e", label: "Medium" },
  low: { bg: "#f3f4f6", fg: "#4b5563", label: "Low" },
};

export default function InsightsPage() {
  const router = useRouter();
  const base = getApiBase();

  const [data, setData] = useState<AIInsights | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    const tok = getStaffToken();
    if (!tok) {
      router.push("/merchant/login");
      return;
    }
    setError(null);
    try {
      const r = await aiInsights(base, tok, getOperatorMerchant()?.id);
      setData(r);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "";
      if (msg.includes("401")) {
        clearStaffToken();
        router.push("/merchant/login");
      } else {
        setError(msg || "Failed to load AI insights");
      }
    } finally {
      setLoading(false);
    }
  }, [base, router]);

  useEffect(() => {
    load();
  }, [load]);

  const claude = data?.generated_by === "claude";

  return (
    <MerchantSidebar active="insights">
      <div className="page-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 }}>
        <div>
          <h1 className="page-title">AI Insights</h1>
          <p className="page-subtitle">
            Your AI growth advisor — an executive read of the business and the next best actions.
          </p>
        </div>
        <button
          className="btn btn-secondary btn-sm"
          disabled={loading}
          onClick={() => {
            setLoading(true);
            load();
          }}
        >
          {loading ? "Analysing…" : "↻ Regenerate"}
        </button>
      </div>

      {error && <div className="alert alert-error">{error}</div>}

      {loading ? (
        <div className="page-loading">
          <div className="spinner" /> Analysing your business…
        </div>
      ) : data ? (
        <>
          {/* Provider badge */}
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14, flexWrap: "wrap" }}>
            <span
              className="badge"
              style={{
                background: claude ? "#ede9fe" : "#e0f2fe",
                color: claude ? "#5b21b6" : "#075985",
                fontWeight: 600,
              }}
            >
              {claude ? `✨ Generated by Claude${data.model ? ` · ${data.model}` : ""}` : "🧮 Rule-based advisor"}
            </span>
            {!claude && (
              <span style={{ fontSize: 12, color: "var(--color-text-muted)" }}>
                Set <code>AI_ENABLED=1</code> + <code>ANTHROPIC_API_KEY</code> to switch this advisor to Claude.
              </span>
            )}
            {data.fallback_reason && (
              <span style={{ fontSize: 12, color: "#9a3412" }}>
                (Claude unavailable — {data.fallback_reason}; showed rule-based advice instead.)
              </span>
            )}
          </div>

          {/* Executive summary */}
          <div className="card" style={{ marginBottom: 20, borderLeft: "4px solid var(--color-primary, #4f46e5)" }}>
            <div className="card-title" style={{ marginBottom: 8 }}>Executive summary</div>
            <p style={{ margin: 0, lineHeight: 1.55, fontSize: 15 }}>{data.summary}</p>
          </div>

          {/* Highlights */}
          {data.highlights.length > 0 && (
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 20 }}>
              {data.highlights.map((h, i) => (
                <span
                  key={i}
                  className="badge"
                  style={{ background: "#f8fafc", color: "#334155", border: "1px solid #e2e8f0", fontSize: 13 }}
                >
                  {h}
                </span>
              ))}
            </div>
          )}

          {/* Recommendations */}
          <div className="card-title" style={{ marginBottom: 12 }}>
            Recommended actions ({data.recommendations.length})
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            {data.recommendations.map((rec, i) => {
              const p = PRIORITY_STYLE[rec.priority] ?? PRIORITY_STYLE.low;
              return (
                <div key={i} className="card" style={{ borderLeft: `4px solid ${p.fg}` }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, marginBottom: 6 }}>
                    <h3 style={{ margin: 0, fontSize: 16 }}>{rec.title}</h3>
                    <span className="badge" style={{ background: p.bg, color: p.fg, fontWeight: 600, whiteSpace: "nowrap" }}>
                      {p.label}
                    </span>
                  </div>
                  <p style={{ margin: "0 0 10px", color: "var(--color-text-muted)", lineHeight: 1.5, fontSize: 14 }}>
                    {rec.rationale}
                  </p>
                  <div style={{ background: "#f8fafc", borderRadius: 6, padding: "8px 12px", fontSize: 14 }}>
                    <strong>Do this:</strong> {rec.action}
                  </div>
                  {rec.metric && (
                    <div style={{ marginTop: 8, fontSize: 12, color: "var(--color-text-muted)" }}>
                      Signal: <strong>{rec.metric}</strong>
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          <p style={{ marginTop: 18, fontSize: 12, color: "var(--color-text-muted)" }}>
            Derived from your live sales, CRM segments, churn risk, RFM, pipeline, and campaign performance.
            Generated {new Date(data.generated_at).toLocaleString()}.
          </p>
        </>
      ) : null}
    </MerchantSidebar>
  );
}
