"""initial schema

Revision ID: 0a0998e7450c
Revises: 
Create Date: 2026-05-26 13:48:42.063665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a0998e7450c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coalitions',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)

    op.create_table('merchants',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('reward_rules',
    sa.Column('scope_type', sa.String(length=12), nullable=False),
    sa.Column('scope_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_rules_scope_id'), ['scope_id'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('brands',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('cuisine_type', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('campaign_type', sa.String(length=32), nullable=False),
    sa.Column('segment_key', sa.String(length=48), nullable=True),
    sa.Column('message_template', sa.String(length=1000), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('coalition_members',
    sa.Column('coalition_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['coalition_id'], ['coalitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coalition_id', 'merchant_id')
    )
    op.create_table('customer_auth_identities',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'identifier', name='uq_identity_provider_identifier')
    )
    with op.batch_alter_table('customer_auth_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_auth_identities_customer_id'), ['customer_id'], unique=False)

    op.create_table('customer_notes',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('author_user_id', sa.String(length=32), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('customer_segments',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_segments_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('customer_tags',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=48), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'customer_id', 'tag', name='uq_customer_tag')
    )
    with op.batch_alter_table('customer_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_tags_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_tags_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('loyalty_accounts',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=12), nullable=False),
    sa.Column('scope_id', sa.String(length=32), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_points', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=12), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('first_visit_at', sa.DateTime(), nullable=True),
    sa.Column('last_visit_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'scope_type', 'scope_id', name='uq_loyalty_scope')
    )
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_scope_id'), ['scope_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('permission_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='uq_user_role_scope')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('campaign_audiences',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_audiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_audiences_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_audiences_customer_id'), ['customer_id'], unique=False)

    op.create_table('campaign_messages',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('to_address', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provider_ref', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_messages_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_messages_customer_id'), ['customer_id'], unique=False)

    op.create_table('outlets',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlets_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('menus',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('outlet_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menus_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menus_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('tables',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('outlet_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outlet_id', 'label', name='uq_table_outlet_label')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('menu_categories',
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_categories_menu_id'), ['menu_id'], unique=False)

    op.create_table('orders',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('outlet_id', sa.String(length=32), nullable=False),
    sa.Column('table_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('order_type', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_table_id'), ['table_id'], unique=False)

    op.create_table('qr_codes',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('outlet_id', sa.String(length=32), nullable=False),
    sa.Column('table_id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=48), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_codes_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_token'), ['token'], unique=True)

    op.create_table('campaign_redemptions',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_redemptions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_redemptions_customer_id'), ['customer_id'], unique=False)

    op.create_table('menu_items',
    sa.Column('category_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_items_category_id'), ['category_id'], unique=False)

    op.create_table('payments',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('reward_redemptions',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('reward_name', sa.String(length=160), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_redemptions_account_id'), ['account_id'], unique=False)

    op.create_table('reward_transactions',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('txn_type', sa.String(length=12), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('rule_code', sa.String(length=48), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_transactions_account_id'), ['account_id'], unique=False)

    op.create_table('menu_modifiers',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_modifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_modifiers_item_id'), ['item_id'], unique=False)

    op.create_table('order_items',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('menu_item_id', sa.String(length=32), nullable=True),
    sa.Column('name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('transactions',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('outlet_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_outlet_id'), ['outlet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_order_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('menu_modifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_modifiers_item_id'))

    op.drop_table('menu_modifiers')
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_transactions_account_id'))

    op.drop_table('reward_transactions')
    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_redemptions_account_id'))

    op.drop_table('reward_redemptions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_category_id'))

    op.drop_table('menu_items')
    with op.batch_alter_table('campaign_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_redemptions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_redemptions_campaign_id'))

    op.drop_table('campaign_redemptions')
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_codes_token'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_table_id'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_merchant_id'))

    op.drop_table('qr_codes')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_table_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_orders_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_brand_id'))

    op.drop_table('orders')
    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_categories_menu_id'))

    op.drop_table('menu_categories')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_tables_merchant_id'))

    op.drop_table('tables')
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menus_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_menus_merchant_id'))

    op.drop_table('menus')
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlets_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_outlets_brand_id'))

    op.drop_table('outlets')
    with op.batch_alter_table('campaign_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_messages_customer_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_messages_campaign_id'))

    op.drop_table('campaign_messages')
    with op.batch_alter_table('campaign_audiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_audiences_customer_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_audiences_campaign_id'))

    op.drop_table('campaign_audiences')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_scope_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_scope_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_customer_id'))

    op.drop_table('loyalty_accounts')
    with op.batch_alter_table('customer_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_tags_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_tags_customer_id'))

    op.drop_table('customer_tags')
    with op.batch_alter_table('customer_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_segments_merchant_id'))

    op.drop_table('customer_segments')
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_notes_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_notes_customer_id'))

    op.drop_table('customer_notes')
    with op.batch_alter_table('customer_auth_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_auth_identities_customer_id'))

    op.drop_table('customer_auth_identities')
    op.drop_table('coalition_members')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_merchant_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_merchant_id'))

    op.drop_table('brands')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('reward_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_rules_scope_id'))

    op.drop_table('reward_rules')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    op.drop_table('merchants')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    op.drop_table('coalitions')
    # ### end Alembic commands ###
