"""rewards catalog, wheel, crm tasks, owner

Revision ID: 285e46b32559
Revises: 0a0998e7450c
Create Date: 2026-05-27 13:01:16.449167
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '285e46b32559'
down_revision: Union[str, None] = '0a0998e7450c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_tasks',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('assignee_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_tasks_assignee_user_id'), ['assignee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_status'), ['status'], unique=False)

    op.create_table('reward_catalog_items',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_catalog_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_catalog_items_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('wheel_segments',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('prize_kind', sa.String(length=12), nullable=False),
    sa.Column('prize_value', sa.Integer(), nullable=False),
    sa.Column('voucher_name', sa.String(length=120), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wheel_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheel_segments_merchant_id'), ['merchant_id'], unique=False)

    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_owner_user_id'))
        batch_op.drop_column('owner_user_id')

    with op.batch_alter_table('wheel_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheel_segments_merchant_id'))

    op.drop_table('wheel_segments')
    with op.batch_alter_table('reward_catalog_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_catalog_items_merchant_id'))

    op.drop_table('reward_catalog_items')
    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_customer_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_assignee_user_id'))

    op.drop_table('crm_tasks')
    # ### end Alembic commands ###
